name: Docker CI compare-models

env:
  PREFIX: cnn_skin_cancer/Docker
  DIRECTORY: compare-models
  DOCKERREPO: seblum/cnn-model
  SOURCEDIR: cnn_skin_cancer/src

on:
  push:
    branches: main
    paths:
      - $SOURCEDIR/compare_models.py
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./${{ env.PREFIX }}/${{ env.DIRECTORY }}/Dockerfile
          push: true
          tags: ${{ env.DOCKERREPO }}:${{ env.DIRECTORY }}
